/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/WK9drcx9iAV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Prata } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function WelcomeSection() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="bg-gray-900 text-white py-4 px-6 md:px-12">
        <div className="container mx-auto flex items-center justify-between">
          <h1 className="text-2xl font-bold">Piedras Preciosas</h1>
          <nav className="hidden md:flex items-center space-x-6">
            <a className="hover:text-gray-300" href="#">
              Inicio
            </a>
            <a className="hover:text-gray-300" href="#">
              Sobre Nosotros
            </a>
            <a className="hover:text-gray-300" href="#">
              Catálogo
            </a>
            <a className="hover:text-gray-300" href="#">
              Contacto
            </a>
          </nav>
          <button className="md:hidden">
            <MenuIcon className="h-6 w-6" />
          </button>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-12 md:py-20 bg-gray-100" id="about">
          <div className="container mx-auto px-6 md:px-12">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <h2 className="text-3xl font-bold mb-4">Bienvenido a Piedras Preciosas</h2>
                <p className="text-gray-700 leading-relaxed">
                  En nuestra tienda, ofrecemos una amplia selección de piedras preciosas y semipreciosas de la más alta
                  calidad. Desde amatistas hasta zafiros, tenemos todo lo que necesitas para complementar tu estilo
                  único.
                </p>
                <p className="text-gray-700 leading-relaxed mt-4">
                  Nuestro equipo de expertos está dedicado a brindarte una experiencia de compra excepcional. Explora
                  nuestra colección y déjate inspirar por la belleza y el poder de estas piedras milenarias.
                </p>
              </div>
              <div>
                <img
                  alt="Piedras Preciosas"
                  className="rounded-lg shadow-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600} />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20" id="gallery">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-3xl font-bold mb-8 text-center">Nuestras Piedras Más Populares</h2>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <div className="rounded-lg overflow-hidden shadow-lg">
                <img
                  alt="Piedra 1"
                  className="w-full h-64 object-cover"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Amatista</h3>
                  <p className="text-gray-700">Una piedra preciosa de color púrpura con propiedades curativas.</p>
                </div>
              </div>
              <div className="rounded-lg overflow-hidden shadow-lg">
                <img
                  alt="Piedra 2"
                  className="w-full h-64 object-cover"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Ópalo</h3>
                  <p className="text-gray-700">Una piedra preciosa con un juego de colores único y cautivador.</p>
                </div>
              </div>
              <div className="rounded-lg overflow-hidden shadow-lg">
                <img
                  alt="Piedra 3"
                  className="w-full h-64 object-cover"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Rubí</h3>
                  <p className="text-gray-700">Una piedra preciosa de color rojo intenso, símbolo de pasión y poder.</p>
                </div>
              </div>
              <div className="rounded-lg overflow-hidden shadow-lg">
                <img
                  alt="Piedra 4"
                  className="w-full h-64 object-cover"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Esmeralda</h3>
                  <p className="text-gray-700">
                    Una piedra preciosa de color verde brillante, símbolo de esperanza y renovación.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20 bg-gray-100" id="catalog">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-3xl font-bold mb-8 text-center">Explora Nuestro Catálogo</h2>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="bg-white rounded-lg shadow-lg p-6">
                <h3 className="text-lg font-bold mb-4">Filtros</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="type">Tipo</Label>
                    <Select className="w-full" id="type">
                      <SelectTrigger>
                        <SelectValue placeholder="Selecciona un tipo" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="amatista">Amatista</SelectItem>
                        <SelectItem value="opalo">Ópalo</SelectItem>
                        <SelectItem value="rubi">Rubí</SelectItem>
                        <SelectItem value="esmeralda">Esmeralda</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="color">Color</Label>
                    <Select className="w-full" id="color">
                      <SelectTrigger>
                        <SelectValue placeholder="Selecciona un color" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="purpura">Púrpura</SelectItem>
                        <SelectItem value="multicolor">Multicolor</SelectItem>
                        <SelectItem value="rojo">Rojo</SelectItem>
                        <SelectItem value="verde">Verde</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="size">Tamaño</Label>
                    <Select className="w-full" id="size">
                      <SelectTrigger>
                        <SelectValue placeholder="Selecciona un tamaño" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="pequeno">Pequeño</SelectItem>
                        <SelectItem value="mediano">Mediano</SelectItem>
                        <SelectItem value="grande">Grande</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="price">Precio</Label>
                    <Select className="w-full" id="price">
                      <SelectTrigger>
                        <SelectValue placeholder="Selecciona un rango de precio" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="bajo">Bajo</SelectItem>
                        <SelectItem value="medio">Medio</SelectItem>
                        <SelectItem value="alto">Alto</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-lg p-6 col-span-2 lg:col-span-2">
                <h3 className="text-lg font-bold mb-4">Resultados</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                  <div className="rounded-lg overflow-hidden shadow-lg">
                    <img
                      alt="Piedra 1"
                      className="w-full h-64 object-cover"
                      height={300}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/300",
                        objectFit: "cover",
                      }}
                      width={300} />
                    <div className="p-4">
                      <h3 className="text-lg font-bold mb-2">Amatista</h3>
                      <p className="text-gray-700">Una piedra preciosa de color púrpura con propiedades curativas.</p>
                      <div className="flex justify-between items-center mt-4">
                        <span className="text-gray-700 font-bold">$50</span>
                        <Button size="sm">Agregar al carrito</Button>
                      </div>
                    </div>
                  </div>
                  <div className="rounded-lg overflow-hidden shadow-lg">
                    <img
                      alt="Piedra 2"
                      className="w-full h-64 object-cover"
                      height={300}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/300",
                        objectFit: "cover",
                      }}
                      width={300} />
                    <div className="p-4">
                      <h3 className="text-lg font-bold mb-2">Ópalo</h3>
                      <p className="text-gray-700">Una piedra preciosa con un juego de colores único y cautivador.</p>
                      <div className="flex justify-between items-center mt-4">
                        <span className="text-gray-700 font-bold">$75</span>
                        <Button size="sm">Agregar al carrito</Button>
                      </div>
                    </div>
                  </div>
                  <div className="rounded-lg overflow-hidden shadow-lg">
                    <img
                      alt="Piedra 3"
                      className="w-full h-64 object-cover"
                      height={300}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/300",
                        objectFit: "cover",
                      }}
                      width={300} />
                    <div className="p-4">
                      <h3 className="text-lg font-bold mb-2">Rubí</h3>
                      <p className="text-gray-700">
                        Una piedra preciosa de color rojo intenso, símbolo de pasión y poder.
                      </p>
                      <div className="flex justify-between items-center mt-4">
                        <span className="text-gray-700 font-bold">$100</span>
                        <Button size="sm">Agregar al carrito</Button>
                      </div>
                    </div>
                  </div>
                  <div className="rounded-lg overflow-hidden shadow-lg">
                    <img
                      alt="Piedra 4"
                      className="w-full h-64 object-cover"
                      height={300}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/300",
                        objectFit: "cover",
                      }}
                      width={300} />
                    <div className="p-4">
                      <h3 className="text-lg font-bold mb-2">Esmeralda</h3>
                      <p className="text-gray-700">
                        Una piedra preciosa de color verde brillante, símbolo de esperanza y renovación.
                      </p>
                      <div className="flex justify-between items-center mt-4">
                        <span className="text-gray-700 font-bold">$125</span>
                        <Button size="sm">Agregar al carrito</Button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-8 px-6 md:px-12" id="contact">
        <div
          className="container mx-auto flex flex-col md:flex-row items-center justify-between">
          <div>
            <h3 className="text-lg font-bold mb-2">Contáctanos</h3>
            <p className="text-gray-400">Estamos aquí para ayudarte con cualquier pregunta o inquietud que tengas.</p>
            <div className="mt-4 flex space-x-4">
              <Link className="text-gray-400 hover:text-white" href="#">
                <MailIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-white" href="#">
                <PhoneIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-white" href="#">
                <FacebookIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-white" href="#">
                <InstagramIcon className="h-6 w-6" />
              </Link>
            </div>
          </div>
          <div className="mt-6 md:mt-0">
            <p className="text-gray-400">© 2023 Piedras Preciosas. Todos los derechos reservados.</p>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function PhoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>)
  );
}
