/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/WK9drcx9iAV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Prata } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function WelcomeSection() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="bg-gradient-to-r from-violet-900 to-purple-800 text-white py-4 px-6 md:px-12 sticky top-0 z-50 shadow-lg">
        <div className="container mx-auto flex items-center justify-between">
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <span className="text-amber-400">💎</span> Piedras Preciosas
          </h1>
          <nav className="hidden md:flex items-center space-x-8">
            <a className="hover:text-amber-300 transition-colors font-medium" href="#">
              Inicio
            </a>
            <a className="hover:text-amber-300 transition-colors font-medium" href="#about">
              Sobre Nosotros
            </a>
            <a className="hover:text-amber-300 transition-colors font-medium" href="#gallery">
              Catálogo
            </a>
            <a className="hover:text-amber-300 transition-colors font-medium" href="#contact">
              Contacto
            </a>
          </nav>
          <button className="md:hidden text-white">
            <MenuIcon className="h-6 w-6" />
          </button>
        </div>
      </header>
      
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-violet-900 via-purple-800 to-indigo-900 text-white py-24 md:py-32">
        <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg width=%2260%22 height=%2260%22 viewBox=%220 0 60 60%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg fill=%22none%22 fill-rule=%22evenodd%22%3E%3Cg fill=%22%23ffffff%22 fill-opacity=%220.05%22%3E%3Cpath d=%22M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z%22/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')] opacity-30"></div>
        <div className="container mx-auto px-6 md:px-12 text-center relative z-10">
          <h2 className="text-4xl md:text-6xl font-bold mb-6">
            Descubre la <span className="text-amber-400">Magia</span> de las Gemas
          </h2>
          <p className="text-xl md:text-2xl text-purple-200 max-w-2xl mx-auto mb-8">
            Piedras preciosas únicas que reflejan tu esencia y elevan tu estilo
          </p>
          <Button className="bg-amber-500 hover:bg-amber-600 text-black font-semibold px-8 py-3 text-lg rounded-full transition-all hover:scale-105">
            Explorar Colección
          </Button>
        </div>
      </section>
      
      <main className="flex-1">
        <section className="py-16 md:py-24 bg-white" id="about">
          <div className="container mx-auto px-6 md:px-12">
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div>
                <span className="text-violet-600 font-semibold text-sm uppercase tracking-wider">Nuestra Historia</span>
                <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900 mt-2">
                  Bienvenido a <span className="text-violet-600">Piedras Preciosas</span>
                </h2>
                <p className="text-gray-600 leading-relaxed text-lg">
                  En nuestra tienda, ofrecemos una amplia selección de piedras preciosas y semipreciosas de la más alta
                  calidad. Desde amatistas hasta zafiros, tenemos todo lo que necesitas para complementar tu estilo
                  único.
                </p>
                <p className="text-gray-600 leading-relaxed mt-4 text-lg">
                  Nuestro equipo de expertos está dedicado a brindarte una experiencia de compra excepcional. Explora
                  nuestra colección y déjate inspirar por la belleza y el poder de estas piedras milenarias.
                </p>
                <div className="mt-8 flex gap-8">
                  <div className="text-center">
                    <div className="text-3xl font-bold text-violet-600">500+</div>
                    <div className="text-gray-500 text-sm">Piedras Únicas</div>
                  </div>
                  <div className="text-center">
                    <div className="text-3xl font-bold text-violet-600">15+</div>
                    <div className="text-gray-500 text-sm">Años de Experiencia</div>
                  </div>
                  <div className="text-center">
                    <div className="text-3xl font-bold text-violet-600">2000+</div>
                    <div className="text-gray-500 text-sm">Clientes Felices</div>
                  </div>
                </div>
              </div>
              <div className="relative">
                <div className="absolute -inset-4 bg-gradient-to-r from-violet-500 to-amber-500 rounded-2xl blur-2xl opacity-20"></div>
                <img
                  alt="Piedras Preciosas"
                  className="rounded-2xl shadow-2xl relative z-10"
                  height={400}
                  src="https://images.unsplash.com/photo-1551122087-f99a4cb0ac98?w=600&q=80"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600} />
              </div>
            </div>
          </div>
        </section>
        <section className="py-16 md:py-24 bg-gradient-to-b from-purple-50 to-white" id="gallery">
          <div className="container mx-auto px-6 md:px-12">
            <div className="text-center mb-12">
              <span className="text-violet-600 font-semibold text-sm uppercase tracking-wider">Colección Destacada</span>
              <h2 className="text-3xl md:text-4xl font-bold mt-2 text-gray-900">Nuestras Piedras Más Populares</h2>
              <p className="text-gray-600 mt-4 max-w-2xl mx-auto">Cada piedra cuenta una historia única de millones de años</p>
            </div>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
              <div className="group bg-white rounded-2xl overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 hover:-translate-y-2">
                <div className="relative overflow-hidden">
                  <img
                    alt="Piedra 1"
                    className="w-full h-64 object-cover group-hover:scale-110 transition-transform duration-500"
                    height={300}
                    src="https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?w=400&q=80"
                    style={{
                      aspectRatio: "300/300",
                      objectFit: "cover",
                    }}
                    width={300} />
                  <div className="absolute inset-0 bg-gradient-to-t from-purple-900/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                </div>
                <div className="p-5">
                  <h3 className="text-lg font-bold mb-2 text-gray-900">Amatista</h3>
                  <p className="text-gray-600 text-sm">Una piedra preciosa de color púrpura con propiedades curativas.</p>
                </div>
              </div>
              <div className="group bg-white rounded-2xl overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 hover:-translate-y-2">
                <div className="relative overflow-hidden">
                  <img
                    alt="Piedra 2"
                    className="w-full h-64 object-cover group-hover:scale-110 transition-transform duration-500"
                    height={300}
                    src="https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&q=80"
                    style={{
                      aspectRatio: "300/300",
                      objectFit: "cover",
                    }}
                    width={300} />
                  <div className="absolute inset-0 bg-gradient-to-t from-purple-900/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                </div>
                <div className="p-5">
                  <h3 className="text-lg font-bold mb-2 text-gray-900">Ópalo</h3>
                  <p className="text-gray-600 text-sm">Una piedra preciosa con un juego de colores único y cautivador.</p>
                </div>
              </div>
              <div className="group bg-white rounded-2xl overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 hover:-translate-y-2">
                <div className="relative overflow-hidden">
                  <img
                    alt="Piedra 3"
                    className="w-full h-64 object-cover group-hover:scale-110 transition-transform duration-500"
                    height={300}
                    src="https://images.unsplash.com/photo-1583937443566-6ade3f8e8e95?w=400&q=80"
                    style={{
                      aspectRatio: "300/300",
                      objectFit: "cover",
                    }}
                    width={300} />
                  <div className="absolute inset-0 bg-gradient-to-t from-purple-900/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                </div>
                <div className="p-5">
                  <h3 className="text-lg font-bold mb-2 text-gray-900">Rubí</h3>
                  <p className="text-gray-600 text-sm">Una piedra preciosa de color rojo intenso, símbolo de pasión y poder.</p>
                </div>
              </div>
              <div className="group bg-white rounded-2xl overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 hover:-translate-y-2">
                <div className="relative overflow-hidden">
                  <img
                    alt="Piedra 4"
                    className="w-full h-64 object-cover group-hover:scale-110 transition-transform duration-500"
                    height={300}
                    src="https://images.unsplash.com/photo-1608042314453-ae338d80c427?w=400&q=80"
                    style={{
                      aspectRatio: "300/300",
                      objectFit: "cover",
                    }}
                    width={300} />
                  <div className="absolute inset-0 bg-gradient-to-t from-purple-900/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                </div>
                <div className="p-5">
                  <h3 className="text-lg font-bold mb-2 text-gray-900">Esmeralda</h3>
                  <p className="text-gray-600 text-sm">
                    Una piedra preciosa de color verde brillante, símbolo de esperanza y renovación.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-16 md:py-24 bg-white" id="catalog">
          <div className="container mx-auto px-6 md:px-12">
            <div className="text-center mb-12">
              <span className="text-violet-600 font-semibold text-sm uppercase tracking-wider">Tienda</span>
              <h2 className="text-3xl md:text-4xl font-bold mt-2 text-gray-900">Explora Nuestro Catálogo</h2>
            </div>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              <div className="bg-gradient-to-br from-purple-50 to-white rounded-2xl shadow-lg p-6 border border-purple-100">
                <h3 className="text-lg font-bold mb-4 text-violet-800 flex items-center gap-2">
                  <span>🔍</span> Filtros
                </h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="type" className="text-gray-700 font-medium">Tipo</Label>
                    <Select className="w-full" id="type">
                      <SelectTrigger className="mt-1 border-purple-200 focus:border-violet-500">
                        <SelectValue placeholder="Selecciona un tipo" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="amatista">Amatista</SelectItem>
                        <SelectItem value="opalo">Ópalo</SelectItem>
                        <SelectItem value="rubi">Rubí</SelectItem>
                        <SelectItem value="esmeralda">Esmeralda</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="color" className="text-gray-700 font-medium">Color</Label>
                    <Select className="w-full" id="color">
                      <SelectTrigger className="mt-1 border-purple-200 focus:border-violet-500">
                        <SelectValue placeholder="Selecciona un color" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="purpura">Púrpura</SelectItem>
                        <SelectItem value="multicolor">Multicolor</SelectItem>
                        <SelectItem value="rojo">Rojo</SelectItem>
                        <SelectItem value="verde">Verde</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="size" className="text-gray-700 font-medium">Tamaño</Label>
                    <Select className="w-full" id="size">
                      <SelectTrigger className="mt-1 border-purple-200 focus:border-violet-500">
                        <SelectValue placeholder="Selecciona un tamaño" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="pequeno">Pequeño</SelectItem>
                        <SelectItem value="mediano">Mediano</SelectItem>
                        <SelectItem value="grande">Grande</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="price" className="text-gray-700 font-medium">Precio</Label>
                    <Select className="w-full" id="price">
                      <SelectTrigger className="mt-1 border-purple-200 focus:border-violet-500">
                        <SelectValue placeholder="Selecciona un rango de precio" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="bajo">Bajo</SelectItem>
                        <SelectItem value="medio">Medio</SelectItem>
                        <SelectItem value="alto">Alto</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </div>
              <div className="bg-white rounded-2xl shadow-lg p-6 col-span-2 lg:col-span-2 border border-gray-100">
                <h3 className="text-lg font-bold mb-4 text-gray-900">Resultados</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                  <div className="group rounded-2xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 bg-white border border-gray-100">
                    <img
                      alt="Piedra 1"
                      className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                      height={300}
                      src="https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?w=400&q=80"
                      style={{
                        aspectRatio: "300/300",
                        objectFit: "cover",
                      }}
                      width={300} />
                    <div className="p-4">
                      <h3 className="text-lg font-bold mb-2 text-gray-900">Amatista</h3>
                      <p className="text-gray-600 text-sm">Una piedra preciosa de color púrpura con propiedades curativas.</p>
                      <div className="flex justify-between items-center mt-4">
                        <span className="text-violet-600 font-bold text-lg">$50</span>
                        <Button size="sm" className="bg-violet-600 hover:bg-violet-700">Agregar</Button>
                      </div>
                    </div>
                  </div>
                  <div className="group rounded-2xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 bg-white border border-gray-100">
                    <img
                      alt="Piedra 2"
                      className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                      height={300}
                      src="https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&q=80"
                      style={{
                        aspectRatio: "300/300",
                        objectFit: "cover",
                      }}
                      width={300} />
                    <div className="p-4">
                      <h3 className="text-lg font-bold mb-2 text-gray-900">Ópalo</h3>
                      <p className="text-gray-600 text-sm">Una piedra preciosa con un juego de colores único y cautivador.</p>
                      <div className="flex justify-between items-center mt-4">
                        <span className="text-violet-600 font-bold text-lg">$75</span>
                        <Button size="sm" className="bg-violet-600 hover:bg-violet-700">Agregar</Button>
                      </div>
                    </div>
                  </div>
                  <div className="group rounded-2xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 bg-white border border-gray-100">
                    <img
                      alt="Piedra 3"
                      className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                      height={300}
                      src="https://images.unsplash.com/photo-1583937443566-6ade3f8e8e95?w=400&q=80"
                      style={{
                        aspectRatio: "300/300",
                        objectFit: "cover",
                      }}
                      width={300} />
                    <div className="p-4">
                      <h3 className="text-lg font-bold mb-2 text-gray-900">Rubí</h3>
                      <p className="text-gray-600 text-sm">
                        Una piedra preciosa de color rojo intenso, símbolo de pasión y poder.
                      </p>
                      <div className="flex justify-between items-center mt-4">
                        <span className="text-violet-600 font-bold text-lg">$100</span>
                        <Button size="sm" className="bg-violet-600 hover:bg-violet-700">Agregar</Button>
                      </div>
                    </div>
                  </div>
                  <div className="group rounded-2xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 bg-white border border-gray-100">
                    <img
                      alt="Piedra 4"
                      className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                      height={300}
                      src="https://images.unsplash.com/photo-1608042314453-ae338d80c427?w=400&q=80"
                      style={{
                        aspectRatio: "300/300",
                        objectFit: "cover",
                      }}
                      width={300} />
                    <div className="p-4">
                      <h3 className="text-lg font-bold mb-2 text-gray-900">Esmeralda</h3>
                      <p className="text-gray-600 text-sm">
                        Una piedra preciosa de color verde brillante, símbolo de esperanza y renovación.
                      </p>
                      <div className="flex justify-between items-center mt-4">
                        <span className="text-violet-600 font-bold text-lg">$125</span>
                        <Button size="sm" className="bg-violet-600 hover:bg-violet-700">Agregar</Button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gradient-to-r from-violet-900 to-purple-800 text-white py-12 px-6 md:px-12" id="contact">
        <div
          className="container mx-auto flex flex-col md:flex-row items-center justify-between gap-8">
          <div>
            <h3 className="text-xl font-bold mb-3 flex items-center gap-2">
              <span className="text-amber-400">💎</span> Contáctanos
            </h3>
            <p className="text-purple-200">Estamos aquí para ayudarte con cualquier pregunta o inquietud que tengas.</p>
            <div className="mt-6 flex space-x-4">
              <Link className="bg-white/10 p-3 rounded-full hover:bg-amber-500 transition-colors" href="#">
                <MailIcon className="h-5 w-5" />
              </Link>
              <Link className="bg-white/10 p-3 rounded-full hover:bg-amber-500 transition-colors" href="#">
                <PhoneIcon className="h-5 w-5" />
              </Link>
              <Link className="bg-white/10 p-3 rounded-full hover:bg-amber-500 transition-colors" href="#">
                <FacebookIcon className="h-5 w-5" />
              </Link>
              <Link className="bg-white/10 p-3 rounded-full hover:bg-amber-500 transition-colors" href="#">
                <InstagramIcon className="h-5 w-5" />
              </Link>
            </div>
          </div>
          <div className="text-center md:text-right">
            <p className="text-purple-200">© 2026 Piedras Preciosas</p>
            <p className="text-purple-300 text-sm mt-1">Todos los derechos reservados</p>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function PhoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>)
  );
}
